// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lyubomirr/meme-generator-app/core/repositories (interfaces: UoWFactory)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	repositories "github.com/lyubomirr/meme-generator-app/core/repositories"
)

// MockUoWFactory is a mock of UoWFactory interface.
type MockUoWFactory struct {
	ctrl     *gomock.Controller
	recorder *MockUoWFactoryMockRecorder
}

// MockUoWFactoryMockRecorder is the mock recorder for MockUoWFactory.
type MockUoWFactoryMockRecorder struct {
	mock *MockUoWFactory
}

// NewMockUoWFactory creates a new mock instance.
func NewMockUoWFactory(ctrl *gomock.Controller) *MockUoWFactory {
	mock := &MockUoWFactory{ctrl: ctrl}
	mock.recorder = &MockUoWFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUoWFactory) EXPECT() *MockUoWFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUoWFactory) Create() repositories.UnitOfWork {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create")
	ret0, _ := ret[0].(repositories.UnitOfWork)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUoWFactoryMockRecorder) Create() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUoWFactory)(nil).Create))
}
